# Generated by Django 4.2.7 on 2026-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_discount_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
