# Generated by Django 4.2.7 on 2026-05-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
