# Generated by Django 4.2.7 on 2026-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Mahalaxmi Sweets & Farsan', max_length=200)),
                ('tagline', models.CharField(default='Taste the Tradition', max_length=255)),
                ('phone', models.CharField(default='9876543210', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_delivery_above', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Shop Setting',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
